### ISSUE TITLE
Unclear what anything does.

### ISSUE THREAD

**Issue by searchqueery** [jmaliksi/onomancer#3]
Instructions on how to use website missing or hard to find. The "what" page, while flavorful, is not very helpful.

**Comment by jmaliksi** [comment]
to what extent do you think instructions are necessary? Definitely have been thinking about how to make the Collect page more understandable, but do you also think instructions are necessary for the upvote/downvote pages and the submission pages?

**Comment by jmaliksi** [comment]
@searchqueery thoughts on the new help page on the collection page?
![Uploading Screen Shot 2020-12-29 at 3.36.28 PM.png…]()

**Comment by jmaliksi** [comment]
@searchqueery thoughts on the new help section on the collection page?

<img width="613" alt="Screen Shot 2020-12-29 at 3 36 28 PM" src="https://user-images.githubusercontent.com/3155720/103320806-b489bd00-49eb-11eb-97a7-b5bd7103321a.png">

**Comment by searchqueery** [comment]
I personally do not know what the collect, pool, and stash pages do. I can tell what the other pages are for, but what each button does is unclear, namely on some of the Regard subpages.

**Comment by searchqueery** [comment]
Sorry, left that comment before seeing the screenshot. Yes, that helps with the second part of my last comment.

**Comment by jmaliksi** [comment]
👍

**Comment by jmaliksi** [comment]
I've amended the header text on those other pages here

Pool: A fleeting glimpse of names within the Tome...

Stash (when empty): An empty stash. You may save names you come across here.

**Comment by searchqueery** [comment]
That clears up everything for me. Thank you!

**Comment by jmaliksi** [comment]
thanks for your input!
